package com.eu.habbo.habbohotel.wired;

public enum WiredConditionType {
    MATCH_SSHOT(0),
    FURNI_HAVE_HABBO(1),
    TRIGGER_ON_FURNI(2),
    TIME_MORE_THAN(3),
    TIME_LESS_THAN(4),
    USER_COUNT(5),
    ACTOR_IN_TEAM(6),
    FURNI_HAS_FURNI(7),
    STUFF_IS(8),
    ACTOR_IN_GROUP(10),
    ACTOR_WEARS_BADGE(11),
    ACTOR_WEARS_EFFECT(12),
    NOT_MATCH_SSHOT(13),
    NOT_FURNI_HAVE_HABBO(14),
    NOT_ACTOR_ON_FURNI(15),
    NOT_USER_COUNT(16),
    NOT_ACTOR_IN_TEAM(17),
    NOT_FURNI_HAVE_FURNI(18),
    NOT_STUFF_IS(19),
    NOT_ACTOR_IN_GROUP(21),
    NOT_ACTOR_WEARS_BADGE(22),
    NOT_ACTOR_WEARS_EFFECT(23),
    DATE_RANGE(24),
    ACTOR_HAS_HANDITEM(25),
    VARIABLE_VALUE_MATCH(26),
    USER_PERFORMS_ACTION(27),
    NOT_USER_PERFORMS_ACTION(28),
    SLC_QUANTITY(29),
    HAS_VARIABLE(30),
    VARIABLE_AGE_MATCH(31),
    SELECTOR_VARIABLE(32),
    SELECTOR_REMOTE(33),
    FILTER_VARIABLE(34),
    TEXT_CONNECTOR(35),
    SELECTOR_USERS_TEAM(36),
    SELECTOR_USERS_HANDITEM(37),
    SELECTOR_USERS_BYACTION(38),
    SELECTOR_USERS_GROUP(39),
    SELECTOR_USERS_BYNAME(40),
    SELECTOR_USERS_BYTYPE(41),
    SELECTOR_USERS_ONFURNI(42),
    SELECTOR_FURNI_ONFURNI(43),
    SELECTOR_FURNI_PICKS(44),
    SELECTOR_FURNI_BYTYPE(45),
    SELECTOR_FURNI_ALTITUDE(46),
    SELECTOR_NEIGHBORHOOD(47),
    SELECTOR_SIGNAL(48),
    FILTER_COUNT(49),
    SELECTOR_AREA(50);

    public final int code;

    WiredConditionType(int code) {
        this.code = code;
    }
}

